### ISSUE TITLE
ایده

### ISSUE THREAD

**Issue by mrcrank79** [ircfspace/tester#1]
درود و خسته نباشید.
یه گزینه خوبی که میشه اضافه کرد این هست که با آیپی هایی که میدیم دونه دونه کانفیگ هایی که درست میشه همشو بشه یه جا کپی کرد و وارد برنامه کنیم و دستی تست کنیم داخل v2ray .
یه گزینه دیگه هم هست اینکه من هرچقدر گشتم سایتی پیدا نکردم که فقط آپلود را جداگانه تست کنه مشکلی که داخل ip هست اینه که اپلود ضعیفه دانلود مشکلی نداره، یه قسمتی طراحی بشه که فقط آپلود رو تست کنه خیلی عالی میشه .

**Comment by ircfspace** [comment]
سلام و ارادت

الانم میشه یه‌جا همشونو کپی کرد. انتهای لیست قرار گرفته

تحت وب امکان تست آپلود رو نداریم فعلن
